### PR TITLE
FIX resources state migration should migrate empty array

### LINKED ISSUE #1124: 2.0 upgrade, refresh not fixing all needed state changes
### Terraform Version, Provider Version and Kubernetes Version
```
❯ terraform -v
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/google v3.53.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.0
+ provider registry.terraform.io/hashicorp/time v0.6.0
```
### Affected Resource(s)

- kubernetes_deployment

### Steps to Reproduce

1. Have a kubernetes_deployment defined with no limits set or limits = null
2. Upgrade to 2.0
3. Run a terraform refresh or plan

### Expected Behavior
What should have happened?
The state was upgraded 

### Actual Behavior
What actually happened?
The following output -
```
Error: missing expected {
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by jrhouston**
### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
TF_ACC=1 go test "/Users/john/dev/hashicorp/terraform-provider-kubernetes/kubernetes" -v -count=1 -run TestAccKubernetesDeployment_regression -timeout 120m
=== RUN   TestAccKubernetesDeployment_regression
--- PASS: TestAccKubernetesDeployment_regression (146.17s)
PASS
ok  	github.com/hashicorp/terraform-provider-kubernetes/kubernetes	154.428s
```

Unit test:

```
go test -run TestUpgradeTemplatePodSpecWithResourcesFieldV0_empty ./kubernetes -v -count=1
=== RUN   TestUpgradeTemplatePodSpecWithResourcesFieldV0_empty
--- PASS: TestUpgradeTemplatePodSpecWithResourcesFieldV0_empty (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-kubernetes/kubernetes	2.131s
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/CHANGELOG.md):

```release-note
FIX resources state migration should migrate empty array
```

### References

Fixes #1124 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

File: kubernetes/resource_kubernetes_deployment_test.go [hunk 1]
```diff
@@ -2715,11 +2714,27 @@ func testAccKubernetesDeploymentConfig_beforeUpdate(name, imageName string) stri
 
           resources {
             limits {
-              memory = "512M"
+              memory = "128Mi"
```
Comment (jrhouston) [inline kubernetes/resource_kubernetes_deployment_test.go:2717]: I changed this just because the test was failing sometimes on my local machine because the kind cluster was running short on memory.

**Review by dak1n1 — APPROVED** [review]
Thanks for the quick fix!

**Comment by redeux** [comment]
Manual test in local looks good! Thanks John!
