### PR TITLE
prevent "name" from crashing due to emtpy map

### LINKED ISSUE #1741: Provider crashes when creating ServiceAccounts
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: `1.0.7`
Kubernetes provider version: `2.11.0`
Kubernetes version: `1.21`
```

### Affected Resource(s)
- kubernetes_service_account

### Terraform Configuration Files
```hcl
data "aws_eks_cluster" "this" {
  name = var.eks_cluster_name
}

data "aws_eks_cluster_auth" "this" {
  name = var.eks_cluster_name
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.this.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.this.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.this.token
}

resource "kubernetes_service_account" "this" {
  count                           = var.create_service_account ? 1 : 0
  automount_service_account_token = true
  metadata {
    annotations = {
      "eks.amazonaws.com/role-arn" = module.iam_assumable_role_admin.iam_role_arn
    }
    name      = local.service_account_name
    namespace = var.service_account_namespace
  }
  image_pull_secret {
    name = var.enable_image_pull_secret ? "docker-config-json" : null
  }
}
```

### Debug Output
https://gist.github.com/jessebye/1dc2ad48b3addbddb3183eeecd7232eb

### Panic Output
n/a

### Steps to Reproduce
1. `terraform apply`

### Expected Behavior
ServiceAccount is created and the TF state is updated correctly.

### Actual Behavior
ServiceAccount **is** created, but the TF state is **not** updated.

### Important Factoids
n/a

### References
n/a

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by BBBmau**
### Description

Fixes #1741 - name not able to be set to null

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
NONE
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

File: kubernetes/structures.go [hunk 1]
```diff
@@ -635,13 +635,14 @@ func flattenLabelSelectorRequirementList(l []metav1.LabelSelectorRequirement) []
...
-	for i, v := range in {
-		m := map[string]interface{}{}
+	att := []interface{}{}
+	for _, v := range in {
 		if v.Name != "" {
-			m["name"] = v.Name
+			m := map[string]interface{}{
+				"name": v.Name,
+			}
+			att = append(att, m)
```
Comment (jrhouston) [inline kubernetes/structures.go:644]: So while this solves the crash in the original issue this PR closes, it actually creates a new problem where the next time you run `terraform plan` you're going to see a diff adding the `image_pull_secret` block again. This is because here we are omitting the block entirely from being set into the state so terraform thinks it needs to be created again. This will happen indefinitely. 

I had a look at what the Kubernetes API actually does here, and if we write an imagePullSecret with the name set to `""` it just ignores it and returns an empty object like this:

```yaml
imagePullSecrets:
- {}
```

So I think what we actually want to do here is remove the `if` statement, so we actually always return the map, and if no name is set then it's a map with the name set to `""`. I did that on this branch and it both fixes the crash, and doesn't cause the diff mentioned above.

**Review by jrhouston — CHANGES_REQUESTED** [review]

File: kubernetes/structures.go [hunk 2]
```diff
@@ -668,9 +668,7 @@ func flattenServiceAccountSecrets(in []api.ObjectReference, defaultSecretName st
 			continue
 		}
 		m := map[string]interface{}{}
-		if v.Name != "" {
```
Comment (jrhouston) [inline kubernetes/structures.go:671]: I don't think we need to update this one – just the `flattenLocalObjectReferenceArray` function above.

**Review by jrhouston — CHANGES_REQUESTED** [review]

**Review by jrhouston — APPROVED** [review]
