### PR TITLE
Some fixes post v2.4.0

### LINKED ISSUE #1341: terraform 0.12 not supported with release 2.4.0
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: Terraform v0.12.31
+ provider.aws v3.52.0
+ provider.external v2.1.0
+ provider.helm v2.2.0
+ provider.kubernetes v2.4.0
+ provider.local v2.1.0
+ provider.null v3.1.0
+ provider.random v2.2.1
+ provider.template v2.2.0

Kubernetes provider version: 2.4.0
Kubernetes version: 1.20
```

### Affected Resource(s)

All kubernetes resources that use the kubernetes provider.

### Steps to Reproduce

Use terraform 0.12.31 

1. `terraform init`
2. `terraform  apply`

3: Output
Error: Incompatible terraform version

  on .terraform/modules/ebs-csi-driver/kubernetes.tf line 1, in provider "kubernetes":
   1: provider "kubernetes" {

**This provider requires Terraform v0.14.8 or above**

### Expected Behavior
Kubernetes provider 2.3.2 runs without problems.

### Actual Behavior
Error: Incompatible terraform version

  on .terraform/modules/ebs-csi-driver/kubernetes.tf line 1, in provider "kubernetes":
   1: provider "kubernetes" {

This provider requires Terraform v0.14.8 or above

### PR DESCRIPTION
**Pull request by alexsomesan**
### Description

This change addresses some issues that made their way into release v2.4.0:

* delays checking the minimum version of Terraform in the manifest resource until after ConfigureProvider
* documents the minimum Terraform version for manifest resources
* aligns environment variable names used to set the feature gate flag for kubernetes_manifest
* fixes a dead link in the documentation

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
BUG FIXES:

* restores compatibility with Terraform versions lower than 0.14.8 (#1341)
```

### References

Fixes #1341 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

File: manifest/provider/configure.go [hunk 1]
```diff
@@ -636,3 +629,21 @@ func (s *RawProviderServer) ConfigureProvider(ctx context.Context, req *tfprotov
...
+			Severity: tfprotov5.DiagnosticSeverityError,
+			Summary:  "Experimental feature not enabled.",
+			Detail:   "The `kubernetes_manifest` resource is an experimental feature and must be explicitly enabled in the provider configuration block.",
+		})
+	}
+	if semver.IsValid(s.hostTFVersion) && semver.Compare(s.hostTFVersion, minTFVersion) < 0 {
+		resp = append(resp, &tfprotov5.Diagnostic{
+			Severity: tfprotov5.DiagnosticSeverityError,
+			Summary:  "Incompatible terraform version",
+			Detail:   fmt.Sprintf("This provider requires Terraform %s or above", minTFVersion),
```
Comment (jrhouston) [inline manifest/provider/configure.go:645]:
```suggestion
			Detail:   fmt.Sprintf("The `kubernetes_manifest` resource requires Terraform %s or above", minTFVersion),
```

**Review by jrhouston — CHANGES_REQUESTED** [review]

File: website/docs/r/manifest.html.markdown [hunk 2]
```diff
@@ -11,8 +11,13 @@ Represents one Kubernetes resource by supplying a `manifest` attribute. The mani
...
 Once applied, the `object` attribute contains the state of the resource as returned by the Kubernetes API, including all default values.
 
-~> **NOTE:** This resource uses [Server-side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) to carry out plan and apply operations. This means the cluster has to be accessible at plan time. We recommend only using this resource for custom resources or resources not yet fully supported by the provider. 
+~> **Prerequisites:** 
 
+* This resource requires API access during planning time. This means the cluster has to be accessible at plan time and thus cannot be created in the same apply operation. We recommend only using this resource for custom resources or resources not yet fully supported by the provider.
+
+* This resource uses [Server-side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) to carry out apply operations. A minimum Kubernetes version of 1.16.x is required, but versions 1.17+ are strongly recommended as the SSA implementation in Kubernetes 1.16.x is incomplete and unstable.
+
+* A minimum Terraform version of 1.14.8 is required to use this resource.
```
Comment (jrhouston) [inline website/docs/r/manifest.html.markdown:20]:
```suggestion
* A minimum Terraform version of 0.14.8 is required to use this resource.
```

**Review by jrhouston — CHANGES_REQUESTED** [review]

File: website/docs/r/manifest.html.markdown (hunk 2 above)
Comment (ifs-marouanehalaoit) [inline website/docs/r/manifest.html.markdown]:
```suggestion
* A minimum Terraform version of 0.14.8 is required to use this resource.
```

**Review by ifs-marouanehalaoit — CHANGES_REQUESTED** [review]

**Review by jrhouston — APPROVED** [review]

File: website/docs/r/manifest.html.markdown [hunk 3]
```diff
@@ -11,8 +11,13 @@ Represents one Kubernetes resource by supplying a `manifest` attribute. The mani
...
 Once applied, the `object` attribute contains the state of the resource as returned by the Kubernetes API, including all default values.
 
-~> **NOTE:** This resource uses [Server-side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) to carry out plan and apply operations. This means the cluster has to be accessible at plan time. We recommend only using this resource for custom resources or resources not yet fully supported by the provider. 
+~> **Prerequisites:** 
 
+* This resource requires API access during planning time. This means the cluster has to be accessible at plan time and thus cannot be created in the same apply operation. We recommend only using this resource for custom resources or resources not yet fully supported by the provider.
+
+* This resource uses [Server-side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) to carry out apply operations. A minimum Kubernetes version of 1.16.x is required, but versions 1.17+ are strongly recommended as the SSA implementation in Kubernetes 1.16.x is incomplete and unstable.
+
+* A minimum Terraform version of 0.14.8 is required to use this resource.
```
Comment (ifs-anthonylecarrer) [inline website/docs/r/manifest.html.markdown:20]: I think this comment is not relevant

Comment (ifs-anthonylecarrer) [reply website/docs/r/manifest.html.markdown:20]: There a lot of other constraints relating to terraform 0.14 on this branch. Is this PR complete to work with RF 0.12 and 0.13 ?

Comment (alexsomesan) [reply website/docs/r/manifest.html.markdown:20]: You think the minimum supported Kubernetes version is not important to communicate to users?

Comment (alexsomesan) [reply website/docs/r/manifest.html.markdown:20]: Which constraints do you suspect might prevent it from working with TF 0.12 / 0.13?
