### PR TITLE
Remove limit for taints in `kubernetes_node_taint` resource

### LINKED ISSUE #2035: kubernetes_node_taint: Too many taint blocks
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version:1.3.5
Kubernetes Provider version:2.18.1
Kubernetes version:1.19.3
```
## Terraform configuration
```hcl
resource "kubernetes_node_taint" "nodetaint" {
  metadata {
    name = "node1"
  }
  taint {
    key    = "taint1"
    value  = "true"
    effect = "NoSchedule"
  }
  taint {
    key    = "taint2"
    value  = "true"
    effect = "NoSchedule"
  }
  force = true
  field_manager = "terraform-taint"
}

```
## Error
```
Error: Too many taint blocks
│ 
│   on test.tf line 10, in resource "kubernetes_node_taint" "nodetaint":
│   10:   taint {
│ 
│ No more than 1 "taint" blocks are allowed
```

### PR DESCRIPTION
**Pull request by BBBmau**
### Description

Fixes #2035

Removes the `MaxItems` line from the "taint" attribute. Should allow the ability of multiple taint blocks if desired.

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
`kubernetes/resource_kubernetes_node_taint.go`: Remove MaxItems from taint attribute
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Review by arybolovlev — DISMISSED** [review]
This PR does not address the issue. Yes, Terraform is not throwing an error message anymore. However, the `kubernetes_node_taint` resource takes into account only the first taint in the list, the rest doesn't apply. As the result, we get diff with every plan run.

Another point here is that tests were not updated to validate changes. I would suggest here the TDD approach. The idea is you first write a test that reproduces an issue without changing the code. In short, the tests should fail at this point. Once you have that done, you make changes in the code and run tests again, if the issue is addressed, the tests will pass.

File: kubernetes/resource_kubernetes_node_taint.go [hunk 1]
```diff
@@ -75,7 +70,7 @@ func resourceKubernetesNodeTaint() *schema.Resource {
 
 func resourceKubernetesNodeTaintCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
 	metadata := expandMetadata(d.Get("metadata").([]interface{}))
-	d.SetId(nodeTaintToId(metadata.Name, d.Get("taint").([]interface{})))
+	d.SetId(nodeTaintToId(fmt.Sprintf("%s", metadata.Name), d.Get("taint").([]interface{})))
```
Comment (jrhouston) [inline kubernetes/resource_kubernetes_node_taint.go:73]: You can remove the call to Sprintf here and just use `metadata.Name` directly.

**Review by jrhouston — CHANGES_REQUESTED** [review]

File: kubernetes/resource_kubernetes_node_taint_test.go [hunk 2]
```diff
@@ -107,3 +136,31 @@ resource "kubernetes_node_taint" "test" {
...
+  }
+  taint {
+    key    = "%s-1"
+    value  = "%s"
+    effect = "%s"
+  }
+  taint {
+    key    = "%s-2"
+    value  = "%s"
+    effect = "%s"
```
Comment (jrhouston) [inline kubernetes/resource_kubernetes_node_taint_test.go:156]: Anywhere you have `"%s"` you can use the`%q` directive instead.

**Comment by BBBmau** [comment]
Tried the case where a user will add taints with the same key but different values. A panic is outputted but the tfstate still shows the applied config.

tfconfig:
```hcl
provider "kubernetes" {
  config_path    = "~/.kube/config"
}

resource "kubernetes_node_taint" "tainttest" {
  metadata {
    name = "minikube"
  }

  taint {
    key    = "node-role.kubernetes.io/example"
    value  = "false"
    effect = "NoSchedule"
  }
    taint {
    key    = "node-role.kubernetes.io/example"
    value  = "true"
    effect = "NoSchedule"
  }
}
```
tfstate:
```
            "taint": [
              {
                "effect": "NoSchedule",
                "key": "node-role.kubernetes.io/example",
                "value": "false"
              },
              {
                "effect": "NoSchedule",
                "key": "node-role.kubernetes.io/example",
                "value": "true"
              }
            ]
```

doing `terraform refresh` turns it back to the state before, but this extra step shouldn't be needed.

File: kubernetes/resource_kubernetes_node_taint_test.go [hunk 3]
```diff
@@ -44,6 +44,35 @@ func TestAccKubernetesResourceNodeTaint_basic(t *testing.T) {
...
+
+	resource.Test(t, resource.TestCase{
+		PreCheck:          func() { testAccPreCheck(t) },
+		IDRefreshName:     resourceName,
+		ProviderFactories: testAccProviderFactories,
+		CheckDestroy:      testAccKubernetesNodeTaintDestroy,
+		Steps: []resource.TestStep{
+			{
+				Config: testAccKubernetesNodeTaintConfig_multipleBasic(),
+				Check: resource.ComposeAggregateTestCheckFunc(
```
[the remark this answers is not in the document]
Comment (BBBmau) [reply kubernetes/resource_kubernetes_node_taint_test.go:61]: I'll probably be removing `testAccKubernetesNodeTaintConfig_removeAllTaints()` test step since we need to have minimum 1 taint unless we remove the `minItems` but it feels a bit pointless to have no taints in the node taint resource.

**Comment by jrhouston** [comment]
@BBBmau This is expected behaviour, you can't set multiple taints with the same key. We should add some validation here so that it fails on the plan instead of generating the error at apply time.

**Comment by jrhouston** [comment]
The list type doesn't support validators so I've pushed some logic that does the validation in a custom diff.

**Comment by jrhouston** [comment]
Now it will show on plan time:

```
terraform plan
╷
│ Error: taint: duplicate taint key "node-role.kubernetes.io/example": taint keys must be unique
│
│   with kubernetes_node_taint.tainttest,
│   on main.tf line 5, in resource "kubernetes_node_taint" "tainttest":
│    5: resource "kubernetes_node_taint" "tainttest" {
│
╵
```

**Review by jrhouston — APPROVED** [review]

**Review by jrhouston — APPROVED** [review]
