### PR TITLE
r/service - allow updating ClusterIP to ExternalName + NodePort to ClusterIP

### LINKED ISSUE #656: change service type from clusterIP to externalName should not preserve clusterIP
### Terraform Version
Terraform v0.12.9
+ provider.kubernetes v1.9.0

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_service

### Debug Output
```
Terraform will perform the following actions:

  # kubernetes_service.resource_nids will be updated in-place
  ~ resource "kubernetes_service" "resource_nids" {
        id                    = "default/nids"
        load_balancer_ingress = []

        metadata {
            annotations      = {}
            generation       = 0
            labels           = {}
            name             = "nids"
            namespace        = "default"
            resource_version = "7466818"
            self_link        = "/api/v1/namespaces/default/services/nids"
            uid              = "d773b104-4d58-4b68-94f1-e38165ac0842"
        }

      ~ spec {
            cluster_ip                  = "10.108.78.67"
            external_ips                = []
            load_balancer_source_ranges = []
            publish_not_ready_addresses = false
            selector                    = {
                "app" = "nids"
            }
            session_affinity            = "None"
          ~ type                        = "ClusterIP" -> "ExternalName"

          - port {
              - name        = "a" -> null
              - node_port   = 0 -> null
              - port        = 80 -> null
              - protocol    = "TCP" -> null
              - target_port = "101" -> null
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
run apply got
`Error: Failed to update service: Service "nids" is invalid: [spec.clusterIP: Forbidden: must be empty for ExternalName services, spec.externalName: Required value]`

### Expected Behavior
clusterIP should not preserve, it's ok to preserve on other types.
``

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
`terraform plan`

### PR DESCRIPTION
**Pull request by DrFaust92**
### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccKubernetesService_'
--- PASS: TestAccKubernetesService_basic (6.49s)
--- PASS: TestAccKubernetesService_nodePort (2.26s)
--- PASS: TestAccKubernetesService_externalName (2.25s)
--- PASS: TestAccKubernetesService_generatedName (2.69s)
--- PASS: TestAccKubernetesService_regression (257.90s)
--- PASS: TestAccKubernetesService_externalName_toClusterIp (4.74s)
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md):

```release-note
resource_kubernetes_service - allow updating ClusterIP to ExternalName
```

### References
Closes #656

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

File: kubernetes/structure_service_spec.go [hunk 1]
```diff
@@ -167,6 +167,13 @@ func patchServiceSpec(keyPrefix, pathPrefix string, d *schema.ResourceData, v *v
 		})
 	}
 	if d.HasChange(keyPrefix + "type") {
+		o, n := d.GetChange(keyPrefix + "type")
+
+		if o.(string) == "ClusterIP" && n.(string) == "ExternalName" {
```
Comment (dak1n1) [inline kubernetes/structure_service_spec.go:172]: This is great! It seems to work reliably, and I like that there's a test for it too. I found some other cases where this logic will be useful. Here's a summary of what I found during my testing:

1. If cluster_ip exists in state already, and we're trying to change the service to type ExternalName, we need to remove cluster_ip. ClusterIP is automatically set by `type: NodePort`, `type: ClusterIP`, and `type: LoadBalancer`. So basically we need to expand the current logic in this PR to handle those types as well.

2. If `spec.ports[0].nodePort` is set, and we're trying to change the service type to ClusterIP, we need to delete nodePort. This spec.[0].nodePort is automatically created by `type: NodePort` and `type: LoadBalancer`, and it can be used with ExternalName. Users can specify this with any type other than `ClusterIP`.

Let me know if I should create a new bug report for number 2. That could be more trouble than it's worth in this PR, so I'll leave that decision to you.

Here's how I think we can cover number 1:

```suggestion
		if n.(string) == "ExternalName" {
```

**Review by dak1n1 — COMMENTED** [review]
The acceptance tests are looking good! I just wanted to expand this logic a little to cover a couple other cases. Let me know what you think

File: kubernetes/structure_service_spec.go (hunk 1 above)
Comment (DrFaust92) [reply kubernetes/structure_service_spec.go]: Thanks for the feeback, first issue makes sense ill test it. for 2 ill add the logic and test to see but no need to wait i think. if i wont respond in a timely manner feel free to merge this and open a new PR.

Comment (DrFaust92) [reply kubernetes/structure_service_spec.go]: Ok, i think i managed to solve the second case as well. not sure this is the nicest solution but this what i was able to cook up quickly. LMK what you think.

Comment (DrFaust92) [reply kubernetes/structure_service_spec.go]: acctest after latest change:

```
--- PASS: TestAccKubernetesService_basic (7.09s)
--- PASS: TestAccKubernetesService_nodePort (4.72s)
--- PASS: TestAccKubernetesService_externalName (2.50s)
--- PASS: TestAccKubernetesService_externalName_toClusterIp (7.16s)
--- PASS: TestAccKubernetesService_generatedName (3.15s)
--- PASS: TestAccKubernetesService_regression (161.28s)
```

**Review by dak1n1 — APPROVED** [review]
Looks great! Tests are passing. All scenarios seem to be covered. Thanks for this extra work!
